### ISSUE TITLE
False positives on "Opening brace must be on a new line immediately after the last modifier" rule

### ISSUE THREAD

**Issue by elenadimitrova** [duaraghav8/Solium#50]
The regex here is failing to detect the new line 
https://github.com/duaraghav8/Solium/blob/master/lib/rules/lbrace.js#L418
When outputting the  `charsBeforeLBrace` this is correctly a new line " "

Perhaps a possible alternative is to compare the `declarationEndingLine` and `bodyStartingLine` and check `bodyStartingLine = declarationEndingLine + 1`?

**Comment by duaraghav8** [comment]
@elenadimitrova thought I'd share with you the problem that caused this F.P. You can skip this if you want. Issue has been resolved and won't occur next version onward.

You were right, the Regex wasn't correct. It detected the newline, but not the (optional) spaces or tabs that followed the newline character.

So, something like:
```js
function foo (
    uint x
)
returns (uint)
{
    bar ();
}
``` 

passes, but something like:
```js
contract Baz {
    function foo (
        uint x
    )
    returns (uint)
    {    //NOTICE THERE IS UNDETECTED SPACE BEFORE THE OPENING BRACE (due to indentation)
        bar ();
    }
}
```

failes because the Regex didn't cater for the indentation.

Thanks for informing

**Comment by duaraghav8** [comment]
solved in v0.2.1

**Comment by cgewecke** [comment]
Still getting this false positive when the last modifier in the list has no function brackets, e.g
```
contract ABC {

    function ham()
        modA(param)
        modB(param)
        modC(param)
        payable
    {
        return 0;
    }
}
```

This is parser issue really. The `payable` token's `location.end.offset` is getting set right before the function's opening left brace, probably because whitespace between the modifier name and the `()` is legal?  This means the regex always tests an empty string, doesn't see the `\n` and fires an error. About to open a PR to Solium with a slightly hacky fix for this but maybe it would be better addressed with changes in solidity-parser or solparse.
